### ISSUE TITLE
Consider GitHub name change

### ISSUE THREAD

**Issue by marioortizmanero** [marioortizmanero/spotify-music-videos#15]
This GitHub page is currently named `Spotify Music Videos`, or `spotify-music-videos` as a codename, even though the actual binary, PyPi and AUR repos are called `spotify-videos` because it's shorter.

Perhaps more consistency between the naming would avoid confusion. Should this repo's name be changed to `spotify-videos`?

Maybe I should think of a more unique name to use when the program is more close to being finished and after finishing #8 and #19. Ideas:
* Spotivids

**Comment by marioortizmanero** [comment]
Reopening this. I haven't released the new version yet so I can still change the name. I don't really like having Spotify in the name because it sounds like the module is limited to Spotify. It still doesn't have APIs for other players but they can easily be added after #30 is finished. Now that there is work being done on the FFT audio synchronization, I was thinking of something like LiveVids?

Ideas:
* LiveVids
* MusicVids

**Comment by felix-hilden** [comment]
Just browsing around, seems like a nice package you've created! Just thought I'd give `vidify` a plus one :D descriptive, memorable and rolls off the tongue 👌

**Comment by marioortizmanero** [comment]
Hey Felix! Thanks a bunch :) I'm also leaning towards `vidify` now. At first it looks a bit weird because of the repeated `i`s, but it's got more personality than `videofy`. There's still a long way to go for the 2.0 release, so there's plenty of time anyway.

**Comment by marioortizmanero** [comment]
Alright I'm going with Vidify! I just made a commit in `next` and it will be released in the 2.0 version.
