### ISSUE TITLE
Logo and icon

### ISSUE THREAD

**Issue by marioortizmanero** [marioortizmanero/spotify-music-videos#26]
A logo and icon are needed for the Qt update. Any help would be greatly appreciated :)

Edit: sorry for not specifying more about them. The style should be simple and material design to fit the UI design at #19

**Comment by xypnox** [comment]
Hi I would like to make the icon for this project.

Here is one that I made: 
<img width="235" alt="Icon" src="https://user-images.githubusercontent.com/25076171/67327209-330be480-f535-11e9-80ff-345a00884ed5.png">

This combines both spotify and youtube and is symbolic to _playing spotify songs in youtube_.

**Comment by marioortizmanero** [comment]
Ooooh that's actually pretty neat, we have a winner!! :smile: 

You can do a PR with the logo saved inside the [images](https://github.com/marioortizmanero/spotify-music-videos/tree/next/images) folder in the `next` branch if you want it to count towards your Hacktoberfest progress.

**Comment by xypnox** [comment]
Sure, I am opening a PR with both PNG and SVG formats.
