### ISSUE TITLE
Empty youtube query when playing music on ps4

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [marioortizmanero/spotify-music-videos#31]
Hello, 

I've found a small bug: 

When I'm using the spotify client (1.1.10-r1) on my pc to control spotify on my ps4 using the "Connect to a device"-function, the search query that is parsed to youtube-dl (2019.11.28) is just "' Official Video'". This causes that whatever youtube video happens to be the first result on youtube for "' Official Video'" is shown:

```
andrew@andrew-gentoo-pc ~ % spotify-videos --debug
[youtube:search] query "' Official Video'": Downloading page 1
[download] Downloading playlist: ' Official Video'
[youtube:search] playlist ' Official Video': Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[youtube] RX0k-I0Je7g: Downloading webpage
[youtube] RX0k-I0Je7g: Downloading video info webpage
[download] Finished downloading playlist: ' Official Video'
```

The underlying problem seems to be that spotify does not send the (correct) info (title, artist, album etc) when playing on another device. This is a screenshot from the kde plasma media applet, which otherwise shows the title, artist and album, it exhibits a similar problem when using the spotify client to control another device:
![Screenshot_20191208_152009](https://user-images.githubusercontent.com/8460628/70390764-4d5b2e00-19ce-11ea-9c1a-08e531f675ed.png)

To circumvent this issue might I suggest to add some sort of if statement that does something like this:

```
if youtube-search-query == ' Official Video':
    do not download video
else:
    download video
```

Also, thank you for making this awesome application, I've really been enjoying it. In fact I like it so much that I went through the trouble of writing an ebuild for it and have submitted it as a [pull request](https://github.com/gentoo/gentoo/pull/13870) to the Gentoo repository. With a bit of luck, (and if my ebuild-writing-skills are good enough) spotify-videos might be available in the gentoo repository soon.

**Comment by marioortizmanero** [comment]
Hi Andrew, thanks a bunch for the contribution!

I'm not sure if I fully understand your issue. You're playing music on your PS4 and controlling the audio from your PC, right? Is this the same way as you can do it with your phone, or is it some kind of special feature on the PS4? Because when I play music on my phone and control it from my PC, everything seems to work fine.

Your solution doesn't download videos when the metadata is empty. But if spotify never sends metadata, nothing would ever be displayed. The only useful part of the app would be the lyrics, which isn't even that reliable. What should be shown in the player then? Some default video like what I suggested at https://github.com/marioortizmanero/spotify-music-videos/issues/22? 

---

I'm very glad you like the app :) Thanks a bunch for uploading it to the Gentoo repos. I'm working towards the [2.0 release](https://github.com/marioortizmanero/spotify-music-videos/pull/25) (to be released after 2020), which brings a ton of improvements. The thing is that with new big version I wanted to change the app's name, because frankly spotify-videos is terrible, and this app isn't meant to be used only with Spotify. Implementing more APIs to use it with players should be quite easy. At first I thought of using spotivids, but it has `spoti` in the name. Or maybe It could be like youtube-dl, which isn't actually limited to youtube. I'm not sure...

I'm telling you this because you might want to change the build after this is finished. I'm a bit stuck on coming up with a name, but I can ping you after releasing 2.0 if you want.

**Comment by AndrewAmmerlaan** [comment]
> I'm not sure if I fully understand your issue. You're playing music on your PS4 and controlling the audio from your PC, right? Is this the same way as you can do it with your phone, or is it some kind of special feature on the PS4? Because when I play music on my phone and control it from my PC, everything seems to work fine.

Yes it is the same feature that you can use to control spotify on your phone (or any other spotify client for that matter). I just tested what happens when I try to control my phone with the spotify client on my PC, and it works as expected. (Playing the correct video and showing the correct lyrics)

Trying to control spotify on my ps4 in the same way results in the behaviour I described in my first post. It will always play the video that happens to be the first result here: https://www.youtube.com/results?search_query=%27official+video%27 . It also doesn't show the lyrics. 

This is what spotify-videos --debug gives me when playing music on my pc:
```
[youtube:search] query "'Laibach - Under The Iron Sky Official Video'": Downloading page 1
[download] Downloading playlist: 'Laibach - Under The Iron Sky Official Video'
[youtube:search] playlist 'Laibach - Under The Iron Sky Official Video': Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[youtube] gwJH_vuVDJ4: Downloading webpage
[youtube] gwJH_vuVDJ4: Downloading video info webpage
[download] Finished downloading playlist: 'Laibach - Under The Iron Sky Official Video'
```

And this is what the kde plasma media widget shows:
![Screenshot_20191208_170231](https://user-images.githubusercontent.com/8460628/70392109-88645e00-19dc-11ea-88bc-023b3e0a57d3.png)

This is what I see on screen:
![Screenshot_20191208_170839](https://user-images.githubusercontent.com/8460628/70392180-6ddeb480-19dd-11ea-9ce3-6595d3228927.png)

This is what I see on screen when playing music on ps4:
![Screenshot_20191208_170923](https://user-images.githubusercontent.com/8460628/70392193-98c90880-19dd-11ea-94c2-cadfeb1642a4.png)
Note that the title of the song is not displayed in the bottom right, it just says 'lyrics not found'. The video that is played is this one: https://www.youtube.com/watch?v=RX0k-I0Je7g (the top result if you search 'official video')

This behaviour, combined with the fact that the kde plasma media widget also doesn't show the song title, artist etc. either. Leads me to conclude that the metadata is not being broadcast at all by the spotify client when playing songs on the ps4. In other words this is most likely a bug in the spotify client itself.

In short:
Normal behaviour:
`[youtube:search] query "'Laibach - Under The Iron Sky Official Video'": Downloading page 1`
PS4 behaviour:
`[youtube:search] query "' Official Video'": Downloading page 1`

> Your solution doesn't download videos when the metadata is empty. But if spotify never sends metadata, nothing would ever be displayed. The only useful part of the app would be the lyrics, which isn't even that reliable. What should be shown in the player then? Some default video like what I suggested at #22?

Showing the album artwork when the video can't be found is a good idea. However, in this case, spotify doesn't seem to be sending metadata at all, thus the album art isn't available either. The intent of my suggestion was not to necessarily to fix this issue, because the issue seems to be that the spotify client is simply not sending metadata at all. Instead the idea behind my suggestion is to handle the exception that the spotify metadata is not available. 

I took a quick browse through the code, currently there is this (line 106 and 107 in main.py):
```
        url = get_url(spotify.artist, spotify.title)
        player.start_video(url)
```

I would suggest to execute this if and only if spotify.artist and spotify.title is not empty.
e.g 
```
        if  spotify.artist and spotify.title: 
             url = get_url(spotify.artist, spotify.title)
             player.start_video(url)
       else:
            print("Did not receive metadata")
```

This would prevent spotify-videos form playing some random video that happens to be the first result for 'Official Video'. Of course the real solution is for spotify to fix that it does not send metadata when connected to PS4, however spotify being a closed source application, the linux client not being officially supported and having to go through their customer support forums makes that that a complex task. Besides, it's probably a good idea anyway to not download a random video if spotify.artist and spotify.title are empty strings.

> I'm very glad you like the app :) Thanks a bunch for uploading it to the Gentoo repos. I'm working towards the 2.0 release (to be released after 2020), which brings a ton of improvements. The thing is that with new big version I wanted to change the app's name, because frankly spotify-videos is terrible, and this app isn't meant to be used only with Spotify. Implementing more APIs to use it with players should be quite easy. At first I thought of using spotivids, but it has spoti in the name. Or maybe It could be like youtube-dl, which isn't actually limited to youtube. I'm not sure...

> I'm telling you this because you might want to change the build after this is finished. I'm a bit stuck on coming up with a name, but I can ping you after releasing 2.0 if you want.

I've subscribed to get updates on new releases in this repository (and the repositories of lyricwikia, python-vlc and pydbus). So I think I should already get an email when there are new releases. About the name, I think Spotvids sounds nice, but I suppose something like MusicVid-dl might be more generic and therefore fit more use cases. In any case, when the time comes, it shouldn't be that much work for me to change the name of the ebuild file and change some other variables. It will take some time for the changes to get merged into the gentoo repository because I'm not an official gentoo developer and therefore all my pull requests require a review from someone who is.

**Comment by marioortizmanero** [comment]
> There I was listening to the relaxing music of 'Vancouver Sleep Clinic' while playing a game on my PS4, when all of a sudden I noticed the lesbian soft-porn on the other monitor. Imagine my confusion.

Hahahah at least the big difference that made you notice the bug!

> In other words this is most likely a bug in the spotify client itself, or something specific to do with the spotify app on the PS4.

I don't have a PS4 myself to test it, but they way you've explained it makes the problem really clear (thanks for the pics and details!).

I was thinking of using a default video for whenever errors like this or #22 happen. Think of [the DVD bouncing](https://www.youtube.com/watch?v=rAjfE9JHO_I) to indicate that the video wasn't found, rather than a black screen. Or something more like [this](https://linuxliaison.org/wp-content/uploads/2017/10/Screenshot-from-2017-10-16-23-05-56.png), I don't know. I should look for one online.

> Of course the real solution is for spotify to fix that it does not send metadata when connected to PS4, however spotify being a closed source application, the linux client not being officially supported and having to go through their customer support forums makes that that a complex task. 

The Linux client is actually officially supported, but only for Ubuntu. Regardless, you could post it on their [forums](https://community.spotify.com/) if you wanted to.

Also, when I uploaded python-lyricwikia to the AUR as a dependency of spotify-videos, I created a [PR in the lyricwikia repo](https://github.com/enricobacis/lyricwikia/pull/7/files) to add a link in the readme for future users. You should do that, too. The maintainer is really nice :)

**Comment by AndrewAmmerlaan** [comment]
> I was thinking of using a default video for whenever errors like this or #22 happen. Think of the DVD bouncing to indicate that the video wasn't found, rather than a black screen. Or something more like this, I don't know. I should look for one online.

VLC has a audio visualization feature that is rather nice, maybe that could be the fallback option.
In theory this should work:
`vlc pulse://alsa_output.pci-0000_00_1f.3.analog-stereo.monitor --audio-visual visual`

However, the thing with that is that it only works in theory, for some reason I haven't been able to actually make it work, but maybe you know something I don't. The other problem with this is that it monitors all the sounds, instead of just spotify, but maybe it is possible to use some pulseaudio trickery to create a spotify-app.monitor virtual device and monitor just that device. Otherwise something like the DVD bounce thing would be nice as well:

Perhaps something like this
```
        if  spotify.artist and spotify.title: # if metadata available, search for video
             url = get_url(spotify.artist, spotify.title)
             if url:                                   # if video can be found, play video
                    player.start_video(url)
             else:                                    # if video can't be found (url is empty) show album cover art
                    player.start_video(spotify.albumart)
         else:                                       # if no metadata, revert to default video
              url = dvd-bounce-url
              player.start(url)
```

> The Linux client is actually officially supported, but only for Ubuntu. Regardless, you could post it on their forums if you wanted to.

I will see if I can find the time to do that later this week

> Also, when I uploaded python-lyricwikia to the AUR as a dependency of spotify-videos, I created a PR in the lyricwikia repo to add a link in the readme for future users. You should do that, too. The maintainer is really nice :)

I will definitely do that once my ebuilds get reviewed and accepted to the Gentoo repository.

**Comment by marioortizmanero** [comment]
> VLC has a audio visualization feature that is rather nice, maybe that could be the fallback option.
In theory this should work:

Ohh that's very interesting, I didn't know about it. But for what I've seen online you have to install plugins for that, which isn't convenient. It could be a very fun idea to implement in the distant future. For now I should stick to the default video, following something similar to what you suggested. The fix will probably be available for the 2.0 version though, in the [next branch](https://github.com/marioortizmanero/spotify-music-videos/tree/next).

Quick question: what do you think about the [name](https://github.com/marioortizmanero/spotify-music-videos/issues/15) Videofy? I can't think of anything better...

Thanks again for your help

**Comment by AndrewAmmerlaan** [comment]
> Ohh that's very interesting, I didn't know about it. But for what I've seen online you have to install plugins for that, which isn't convenient. It could be a very fun idea to implement in the distant future. For now I should stick to a default video, following something similar to what you suggested. The fix will probably be available for the 2.0 version though, in the next branch.

Some basic visualizers are included by default unless I'm mistaken, e.g. a simple bar spectrum (`--audio-visual visual`). Only if you want to use projectm (`--audio-visual projectM`) as visualization do you have to install it as a plugin. (or build vlc with that flag enabled). ProjectM then has the feature to install more fancy visualizers. In any case, visualizers don't seem to be working for anything that is not a audio file at the moment, so for now I think it would indeed be best to stick with a default video.

> Quick question: what do you think about the name Videofy? I can't think of anything better...

I like it, this name seems to suggest turning audio into video, which is rather fitting I think.

**Comment by marioortizmanero** [comment]
Using these audio visualizations would also only be avaliable on VLC and this app is supposed to be able to support any player. I'll leave that for the future and find a default video to play for now.

I also thought of Vidify, but when written down it looks a bit weird to me. But yeah it's got more personality. Not really sure...

**Comment by marioortizmanero** [comment]
Fixed in the 2.0 release! This image is shown now when the video wasn't found:

![img](https://linuxliaison.org/wp-content/uploads/2017/10/Screenshot-from-2017-10-16-23-05-56.png)

I didn't end up using the album art because if the metadata is empty, most likely the album will be empty too. Besides, that's only available on the Spotify web API. Apart from that, I added an error message indicating to check the debug mode for more. Closing this issue now.

**Comment by AndrewAmmerlaan** [comment]
> Also, I've added a link to the Gentoo repo in the README for when it's uploaded. Closing this issue now.

Awesome, thank you. The ebuild submission processes is taking a bit longer than I expected, because I made several mistakes in my initial attempts. And also because I made quite a lot of PR's for another package that I updated. I think I almost got it right now, hopefully I will get them approved next week.

> Besides, that's only available on the Spotify web API.

I'm not sure how it works but the plasma media widget can (somehow) find the album art, see also the screenshots in my previous posts. Using KDE connect I can even get the album art on my phone's lock screen when listening to spotify on my PC. I think they use the [MPRIS](https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/#index3h4) `artUrl` property:
```
mpris:artUrl

URI: The location of an image representing the track or album. Clients should not assume this will continue to exist when the media player stops giving out the URL.
```
So perhaps there is someway to show album art without the Web API anyway. But then again, it might not be worth the trouble because in this specific case where artist and title are unavailable `artUrl` is empty as well.

**Comment by marioortizmanero** [comment]
Oh I forgot that DBus also provides the album art! It returns all these entries:

```python
{'mpris:trackid': 'spotify:track:0pBm7wct4JxWDy7RlKASgs', 'mpris:length': 232026000, 'mpris:artUrl': 'https://open.spotify.com/image/ab67616d00001e02a4046a305cc690effa4430bf', 'xesam:album': 'Slow Ride', 'xesam:albumArtist': ['Foghat'], 'xesam:artist': ['Foghat'], 'xesam:autoRating': 0.13, 'xesam:discNumber': 1, 'xesam:title': 'What a Shame', 'xesam:trackNumber':4, 'xesam:url': 'https://open.spotify.com/track/0pBm7wct4JxWDy7RlKASgs'}
```

For this specific issue I don't think it's worth it (hopefully the Spotify devs will take care of that and there are more important priorities). But I could save that info for other future features. Or maybe if I could know if the found video is relevant enough to display it, rather than only doing it when 0 results are found. But that seems impossible for now, I even created an issue when I started programming this app: https://github.com/ytdl-org/youtube-dl/issues/22179.
