### ISSUE TITLE
Absolute paths for icons

### ISSUE THREAD

**Issue by marioortizmanero** [marioortizmanero/spotify-music-videos#37]
As pointed out by #34, the paths for icons and such don't work correctly if the app isn't launched from the same folder. Suggestion:

```python
import os

CURPATH = os.path.dirname(os.path.abspath(__file__))
def respath(f):
    return os.path.join(CURPATH, f)

class Res:
    icon = respath("vidify/gui/res/icon.svg")

# prints /home/mario/Downloads/pytest/vidify/gui/res/icon.svg
print(Res.icon)
```

**Comment by AndrewAmmerlaan** [comment]
This fixes:
```
qt.svg: Cannot open file '/home/andrew/vidify/gui/res/icon.svg', because: No such file or directory
qt.svg: Cannot open file '/home/andrew/vidify/gui/res/icon.svg', because: No such file or directory
```

But if I `rm ~/.config/vidifiy/* && vidify`:
```
qt.svg: Cannot open file 'vidify/gui/res/api_icons/mpris.svg', because: No such file or directory
qt.svg: Cannot open file 'vidify/gui/res/api_icons/spotify/swspotify.svg', because: No such file or directory
qt.svg: Cannot open file 'vidify/gui/res/api_icons/spotify/web.svg', because: No such file or directory
```

I think `vidify/api/__init__.py` needs a similar fix

**Comment by marioortizmanero** [comment]
Fixed it! I just added the entries for API icons in `Res` too. Also, as a tip: if you pass a nonexistent API with `--api`, the initial screen will appear again. You don't have to remove the config file.

Thanks for the help.

**Comment by AndrewAmmerlaan** [comment]
> Fixed it!

Awesome, it works like a charm now, thank you
![Screenshot_20200102_115757](https://user-images.githubusercontent.com/8460628/71663870-25ee4b80-2d57-11ea-857c-2c68d8087ce0.png)
