### ISSUE TITLE
Square icons and .desktop files

### ISSUE THREAD

**Issue by marioortizmanero** [marioortizmanero/spotify-music-videos#38]
Suggested in #34:

> I have made the ebuild to also create a `.desktop` file for vidify. As icon it's using the logo files in the images directory. However, logo.png and logo.svg aren't square images. (Almost) All of the other icon files in `/usr/share/icons` and `/usr/share/pixmaps` are square, this seems to be the convention. KDE (and maybe other DE's too) rescale all icons to fit inside the menu's and launchers. This makes the vidify icon be kinda stretched:

![Screenshot_20200101_145848](https://user-images.githubusercontent.com/8460628/71643020-123dd900-2cb4-11ea-9c97-dd90ae72a822.png)

> It's not really important now, but maybe for in the future it would be nice to have an additional square icon file for .desktop files and launchers. I think it could be just the same logo.{png,svg} with some additional empty space above and below to make it 512x512. That should prevent it from being stretched in menus and launchers.

**Comment by marioortizmanero** [comment]
Wait, @AndrewAmmerlaan have you tried to use the icon in `vidify.gui.res` instead of the one in `images`? That one is square and is 64x64. Or should I make it a 256x256 instead? Also, do you need the `.png` icon, or is the `.svg` enough?

**Comment by AndrewAmmerlaan** [comment]
>Wait, @AndrewAmmerlaan have you tried to use the icon in vidify.gui.res instead of the one in images? That one is square and is 64x64. Or should I make it a 256x256 instead? Also, do you need the .png icon, or is the .svg enough?

Aah, nice, that looks a lot better, Thanks

![Screenshot_20200101_185008](https://user-images.githubusercontent.com/8460628/71644379-92ba0500-2cc7-11ea-8e1a-62cb2dcbdb2f.png)

**Comment by marioortizmanero** [comment]
That's great! I even modified that icon a bit to give it a [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) touch and make it look more like an icon.
