### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by marioortizmanero** [marioortizmanero/spotify-music-videos#43]
Suggestion by @AndrewAmmerlaan:

> Just yesterday I was working on an update to an ebuild for [QDarkStyleSheet](https://github.com/ColinDuquesnoy/QDarkStyleSheet), when I thought you might be interested in that package to. It's a dark stylesheet for PyQt5/PySide2/QtPy applications, it's the stylesheet that is used by the Spyder IDE. I haven't tested it but something as simple as this might work to implement a dark mode:
```
if use_darkstyle == True: # read `use_darkstyle` from `sys.argv` or config file
      import qdarkstyle
      app.setStyleSheet(qdarkstyle.load_stylesheet_from_environment()) # This may or may not require `QT_API` to be set
```

> I can't really test it at the moment because I have an exam upcoming that I should be studying for. So I'm not sure if it works or if it looks good (screenshots on github look nice though), but it might be worth investigating because it would be a very quick and simple way to implement a dark mode.

I was thinking of modifying the values of `vidify.gui.Colors`, but this seems like a much better idea. I'll get on this in the future as there are more important features to be finished (#19 mostly).

**Comment by AndrewAmmerlaan** [comment]
Here's a screenshot of what it looks like with `app.setStyleSheet(qdarkstyle.load_stylesheet_from_environment())`
![Screenshot_20200105_140909](https://user-images.githubusercontent.com/8460628/71780605-f80e3e80-2fc4-11ea-935a-d0946be89594.png)

**Comment by marioortizmanero** [comment]
Looks really nice.

But `QT_API` has to be set before calling `app.setStyleSheet(qdarkstyle.load_stylesheet_from_environment())`, right? How about something like this, but it's a bit nasty:

```python
try:
    import PyQt5
    import PyQt5.QtWebEngineWidgets
except ImportError:
    try:
        import PySide2
    except ImportError:
        # unexpected
        app.setStyleSheet(qdarkstyle.load_stylesheet_from_environment())
    else:
        app.setStyleSheet(qdarkstyle.load_stylesheet_pyside())
else:
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt())
```

**Comment by AndrewAmmerlaan** [comment]
> But does QT_API have to be set before calling app.setStyleSheet(qdarkstyle.load_stylesheet_from_environment())

That is what is says on the QDarkStyle github, but it worked just fine for me without setting it, I think it reverts to the default `QT_API=PyQt5` if the variable is not set. The disadvantage of hardcoding `QT_API` would be that we would lose the ability to easily toggle between PyQt5 and PySide2.

**Comment by marioortizmanero** [comment]
It's curious because I'm using PySide2, without even having PyQt5 installed, and it works with that function.

**Comment by AndrewAmmerlaan** [comment]
> It's curious because I'm using PySide2, without even having PyQt5 installed

This is from the README of QDarkStyleSheet:
```
import sys
import qdarkstyle
import os

# set the environment variable to use a specific wrapper
# it can be set to pyqt, pyqt5, pyside or pyside2 (not implemented yet)
# you do not need to use QtPy to set this variable
os.environ['QT_API'] = 'pyqt'

# import from QtPy instead of doing it directly
# note that QtPy always uses PyQt5 API
from qtpy import QtWidgets

# create the application and the main window
app = QtWidgets.QApplication(sys.argv)
window = QtWidgets.QMainWindow()

# setup stylesheet
app.setStyleSheet(qdarkstyle.load_stylesheet_from_environment())

# run
window.show()
app.exec_()
```

There are also examples for using PyQt5 and PySide2 specifically:

```
import sys
import qdarkstyle
from PyQt5 import QtWidgets

# create the application and the main window
app = QtWidgets.QApplication(sys.argv)
window = QtWidgets.QMainWindow()

# setup stylesheet
app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())

# run
window.show()
app.exec_()
```

As I understand it, the `qdarkstyle.load_stylesheet_from_environment()` function is specific to `QtPy`. I therefore expect it to behave similarly to QtPy: Use PyQt5 if available, and `QT_API` is not set. Use foo if `QT_API=foo` and available. If you don't have PyQt5, then it will use whatever is available.

**Comment by AndrewAmmerlaan** [comment]
Found this in `__init.py__`:
```
 # Get values from QT_API
    try:
        qt_api = os.environ['QT_API']
    except KeyError as err:
        # Log this error just if using QT_API
        if not is_pyqtgraph:
            _logger().error("QT_API does not exist, do os.environ['QT_API']= "
                            "and choose one option from %s", QT_API_VALUES)
```
It seems it does require `QT_API` to be non-empty. However qtpy takes care of this already. This is from QtPy's `__init.py__`:
```
# Setting a default value for QT_API
os.environ.setdefault(QT_API, 'pyqt5')

API = os.environ[QT_API].lower()
initial_api = API

assert API in (PYQT5_API + PYQT4_API + PYSIDE_API + PYSIDE2_API)

is_old_pyqt = is_pyqt46 = False
PYQT5 = True
PYQT4 = PYSIDE = PYSIDE2 = False

# When `FORCE_QT_API` is set, we disregard
# any previously imported python bindings.
if os.environ.get('FORCE_QT_API') is not None:
    if 'PyQt5' in sys.modules:
        API = initial_api if initial_api in PYQT5_API else 'pyqt5'
    elif 'PySide2' in sys.modules:
        API = initial_api if initial_api in PYSIDE2_API else 'pyside2'
    elif 'PyQt4' in sys.modules:
        API = initial_api if initial_api in PYQT4_API else 'pyqt4'
    elif 'PySide' in sys.modules:
        API = initial_api if initial_api in PYSIDE_API else 'pyside'
```

Therefore, if QT_API is not set by the user it will default to `pyqt5`. But if it then can't find `PyQt5` it will go to the next `elif` case: `PySide2`.

**Comment by marioortizmanero** [comment]
> It should be possible to first import the qdarkstyle style-sheet and then override/add specific values as needed, right?

Yes but it will require a couple changes in the `vidify.gui` module because the resources are listed statically. It seems to be really easy for what you say, so I'm on it.

**Comment by marioortizmanero** [comment]
Dark mode implemented in the last commit! Please let me know if you have any issues.

![image](https://user-images.githubusercontent.com/25647296/71781427-1a0cbe80-2fcf-11ea-8f03-556110dea279.png)

**Comment by AndrewAmmerlaan** [comment]
> Dark mode implemented in the last commit! Please let me know if you have any issues.

Awesome, so far it seems to work perfectly, thank you :)
